app = "bike-brigade"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  APP_ENV = "production"

[deploy]
  release_command = "/app/bin/bike_brigade eval BikeBrigade.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
#  http_checks = []
  internal_port = 4000
  protocol = "tcp"
#  script_checks = []

  [services.concurrency]
    hard_limit = 500
    soft_limit = 100

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[metrics]
port = 4021
path = "/metrics"