#!/usr/bin/env bash
source "$(dirname "$0")/utils.sh"

set -e

if [ "$1" == "prod" ]; then
  wrap_nix_shell "flyctl logs"
elif [ "$1" == "staging" ]; then
  wrap_nix_shell "flyctl logs -c fly.staging.toml"
else
  echo "usage: scripts/logs <prod|staging>"
fi
