#!/usr/bin/env bash
source "$(dirname "$0")/utils.sh"

set -e
if [ "$1" == "prod" ]; then
  wrap_nix_shell "flyctl ssh console"
elif [ "$1" == "staging" ]; then
  wrap_nix_shell "flyctl ssh console -c fly.staging.toml"
else
  echo "usage: scripts/remote_console <prod|staging>"
fi
