#!/usr/bin/env bash
source "$(dirname "$0")/utils.sh"

set -e

if [ "$PROD_DATABASE_URL" == "" ]; then
  echo 'Missing $PROD_DATABASE_URL'
  exit 1
fi

if [ "$STAGING_DATABASE_URL" == "" ]; then
  echo 'Missing $STAGING_DATABASE_URL'
  exit 1
fi

DUMP_PATH="$(dirname "$0")/../tmp/db_dump"

#!/bin/bash
function finish {
  echo "Cleaning up"
  rm $DUMP_PATH
}
trap finish EXIT

echo "Dumping production database"
wrap_nix_shell "pg_dump $PROD_DATABASE_URL -Fc -f $DUMP_PATH"
echo "Restoring to staging"
wrap_nix_shell "pg_restore --clean --no-acl -d $STAGING_DATABASE_URL $DUMP_PATH"
echo "Staging restore complete"
